/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaz.dashboard.dashboard;

import com.interfaz.dashboard.ajustes.ajustes;
import java.awt.Color;
import java.awt.Frame;
import com.interfaz.caja.inicio;
import com.interfaz.loader.LoaderService;
import java.awt.Desktop;
import java.net.URI;
import com.interfaz.loader.loader;


/**
 *
 * @author EstudianteUC
 */
public class dashboard1 extends javax.swing.JFrame {

    /**
     * Creates new form dashboard1
     */
    public dashboard1() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void cerrarTodo() {
        for (Frame frame : Frame.getFrames()) {
            frame.dispose();
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new com.interfaz.dashboard.dashboard.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn = new com.interfaz.dashboard.dashboard.PanelRound();
        btnDash = new javax.swing.JLabel();
        btn2 = new com.interfaz.dashboard.dashboard.PanelRound();
        btnRepor = new javax.swing.JLabel();
        btn3 = new com.interfaz.dashboard.dashboard.PanelRound();
        btnTrans = new javax.swing.JLabel();
        btn4 = new com.interfaz.dashboard.dashboard.PanelRound();
        btnAjust = new javax.swing.JLabel();
        btn5 = new com.interfaz.dashboard.dashboard.PanelRound();
        btnSopor = new javax.swing.JLabel();
        btn7 = new com.interfaz.dashboard.dashboard.PanelRound();
        btnStart = new javax.swing.JLabel();
        bg1 = new com.interfaz.dashboard.dashboard.PanelRound();
        showDisp = new com.interfaz.dashboard.dashboard.PanelRound();
        txtDisp = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelRound1 = new com.interfaz.dashboard.dashboard.PanelRound();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        compDash4 = new com.interfaz.dashboard.dashboard.PanelRound();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panelRound7 = new com.interfaz.dashboard.dashboard.PanelRound();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        compDash5 = new com.interfaz.dashboard.dashboard.PanelRound();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        panelRound8 = new com.interfaz.dashboard.dashboard.PanelRound();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        compDash6 = new com.interfaz.dashboard.dashboard.PanelRound();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        panelRound9 = new com.interfaz.dashboard.dashboard.PanelRound();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        compDash7 = new com.interfaz.dashboard.dashboard.PanelRound();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        panelRound10 = new com.interfaz.dashboard.dashboard.PanelRound();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txts12 = new javax.swing.JLabel();
        txts13 = new javax.swing.JLabel();
        txts14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(245, 245, 245));
        header.setRoundBottomRight(60);
        header.setRoundTopRight(60);

        jLabel1.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Administrador");

        jLabel2.setFont(new java.awt.Font("Red Hat Display", 1, 20)); // NOI18N
        jLabel2.setText("KARINA RUEDA");

        btn.setBackground(new java.awt.Color(230, 230, 230));
        btn.setRoundBottomLeft(30);
        btn.setRoundBottomRight(30);
        btn.setRoundTopLeft(30);
        btn.setRoundTopRight(30);

        btnDash.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        btnDash.setForeground(new java.awt.Color(102, 102, 102));
        btnDash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDash.setText("DASHBOARD");
        btnDash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLayout = new javax.swing.GroupLayout(btn);
        btn.setLayout(btnLayout);
        btnLayout.setHorizontalGroup(
            btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnLayout.setVerticalGroup(
            btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDash, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn2.setBackground(new java.awt.Color(230, 230, 230));
        btn2.setRoundBottomLeft(30);
        btn2.setRoundBottomRight(30);
        btn2.setRoundTopLeft(30);
        btn2.setRoundTopRight(30);

        btnRepor.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        btnRepor.setForeground(new java.awt.Color(102, 102, 102));
        btnRepor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRepor.setText("REPORTE");
        btnRepor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRepor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn2Layout = new javax.swing.GroupLayout(btn2);
        btn2.setLayout(btn2Layout);
        btn2Layout.setHorizontalGroup(
            btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn2Layout.createSequentialGroup()
                .addComponent(btnRepor, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        btn2Layout.setVerticalGroup(
            btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRepor, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn3.setBackground(new java.awt.Color(230, 230, 230));
        btn3.setRoundBottomLeft(30);
        btn3.setRoundBottomRight(30);
        btn3.setRoundTopLeft(30);
        btn3.setRoundTopRight(30);

        btnTrans.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        btnTrans.setForeground(new java.awt.Color(102, 102, 102));
        btnTrans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTrans.setText("TRANSACCIONES");
        btnTrans.setToolTipText("");
        btnTrans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn3Layout = new javax.swing.GroupLayout(btn3);
        btn3.setLayout(btn3Layout);
        btn3Layout.setHorizontalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn3Layout.createSequentialGroup()
                .addComponent(btnTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn3Layout.setVerticalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTrans, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn4.setBackground(new java.awt.Color(230, 230, 230));
        btn4.setRoundBottomLeft(30);
        btn4.setRoundBottomRight(30);
        btn4.setRoundTopLeft(30);
        btn4.setRoundTopRight(30);

        btnAjust.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        btnAjust.setForeground(new java.awt.Color(102, 102, 102));
        btnAjust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAjust.setText("AJUSTES");
        btnAjust.setToolTipText("");
        btnAjust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAjustMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAjustMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAjustMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn4Layout = new javax.swing.GroupLayout(btn4);
        btn4.setLayout(btn4Layout);
        btn4Layout.setHorizontalGroup(
            btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn4Layout.createSequentialGroup()
                .addComponent(btnAjust, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn4Layout.setVerticalGroup(
            btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAjust, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn5.setBackground(new java.awt.Color(230, 230, 230));
        btn5.setRoundBottomLeft(30);
        btn5.setRoundBottomRight(30);
        btn5.setRoundTopLeft(30);
        btn5.setRoundTopRight(30);

        btnSopor.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        btnSopor.setForeground(new java.awt.Color(102, 102, 102));
        btnSopor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSopor.setText("SOPORTE");
        btnSopor.setToolTipText("");
        btnSopor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSopor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSoporMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSoporMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn5Layout = new javax.swing.GroupLayout(btn5);
        btn5.setLayout(btn5Layout);
        btn5Layout.setHorizontalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn5Layout.createSequentialGroup()
                .addComponent(btnSopor, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn5Layout.setVerticalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSopor, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn7.setBackground(new java.awt.Color(170, 0, 0));
        btn7.setRoundBottomLeft(30);
        btn7.setRoundBottomRight(30);
        btn7.setRoundTopLeft(30);
        btn7.setRoundTopRight(30);

        btnStart.setBackground(new java.awt.Color(170, 0, 0));
        btnStart.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnStart.setText("INICIAR OPERACIONES");
        btnStart.setToolTipText("");
        btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStartMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStartMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn7Layout = new javax.swing.GroupLayout(btn7);
        btn7.setLayout(btn7Layout);
        btn7Layout.setHorizontalGroup(
            btn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn7Layout.createSequentialGroup()
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn7Layout.setVerticalGroup(
            btn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        bg1.setBackground(new java.awt.Color(255, 255, 255));
        bg1.setRoundBottomLeft(30);
        bg1.setRoundBottomRight(30);
        bg1.setRoundTopLeft(30);
        bg1.setRoundTopRight(30);
        bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showDisp.setBackground(new java.awt.Color(102, 204, 0));
        showDisp.setRoundBottomLeft(20);
        showDisp.setRoundBottomRight(20);
        showDisp.setRoundTopLeft(20);
        showDisp.setRoundTopRight(20);

        javax.swing.GroupLayout showDispLayout = new javax.swing.GroupLayout(showDisp);
        showDisp.setLayout(showDispLayout);
        showDispLayout.setHorizontalGroup(
            showDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        showDispLayout.setVerticalGroup(
            showDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        bg1.add(showDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtDisp.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        txtDisp.setForeground(new java.awt.Color(51, 51, 51));
        txtDisp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDisp.setText("Acceso Total   ");
        txtDisp.setToolTipText("");
        txtDisp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDisp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDispMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDispMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDispMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDispMousePressed(evt);
            }
        });
        bg1.add(txtDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 50));

        jLabel12.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cerrar Sesion");
        jLabel12.setToolTipText("");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bg1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Red Hat Display", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Bienvenida Karina.");

        jLabel4.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("INICIO");

        jLabel18.setFont(new java.awt.Font("Red Hat Display", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 255));
        jLabel18.setText("Novedades de la Version 1.0 beta");

        panelRound1.setBackground(new java.awt.Color(245, 245, 245));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);

        jLabel37.setBackground(new java.awt.Color(170, 0, 0));
        jLabel37.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 153, 0));
        jLabel37.setText("6261");

        jLabel38.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("Al mes: ");

        jLabel41.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel41.setText("Dinero Recaudado al dia:");

        jLabel42.setBackground(new java.awt.Color(170, 0, 0));
        jLabel42.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 153, 0));
        jLabel42.setText("S/ 2156.00");

        jLabel43.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel43.setText("Ventas Efectuadas:");

        jLabel44.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(102, 102, 102));
        jLabel44.setText("Al dia: ");

        jLabel39.setBackground(new java.awt.Color(170, 0, 0));
        jLabel39.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 153, 0));
        jLabel39.setText("45");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(259, 259, 259))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel41))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound1Layout.createSequentialGroup()
                            .addComponent(jLabel43)
                            .addGap(5, 5, 5)
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel41)))
                .addGap(30, 30, 30))
        );

        compDash4.setBackground(new java.awt.Color(245, 245, 245));
        compDash4.setRoundBottomLeft(60);
        compDash4.setRoundBottomRight(60);
        compDash4.setRoundTopLeft(60);
        compDash4.setRoundTopRight(60);

        jLabel21.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel21.setText("SUBIR PRODUCTO");

        jLabel22.setFont(new java.awt.Font("Red Hat Display", 0, 14)); // NOI18N
        jLabel22.setText("<html>Actualiza tu base de datos constatemente <br >para evitar falta de stock.</html>");

        panelRound7.setBackground(new java.awt.Color(170, 0, 0));
        panelRound7.setRoundBottomLeft(30);
        panelRound7.setRoundBottomRight(30);
        panelRound7.setRoundTopLeft(30);
        panelRound7.setRoundTopRight(30);

        jLabel23.setFont(new java.awt.Font("Red Hat Display", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Continuar");

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/caja.png"))); // NOI18N

        javax.swing.GroupLayout compDash4Layout = new javax.swing.GroupLayout(compDash4);
        compDash4.setLayout(compDash4Layout);
        compDash4Layout.setHorizontalGroup(
            compDash4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compDash4Layout.createSequentialGroup()
                .addGroup(compDash4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(compDash4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(compDash4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(panelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(compDash4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel24)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        compDash4Layout.setVerticalGroup(
            compDash4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, compDash4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        compDash5.setBackground(new java.awt.Color(245, 245, 245));
        compDash5.setRoundBottomLeft(60);
        compDash5.setRoundBottomRight(60);
        compDash5.setRoundTopLeft(60);
        compDash5.setRoundTopRight(60);

        jLabel25.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel25.setText("RETIRA TUS GANANCIAS");

        jLabel26.setFont(new java.awt.Font("Red Hat Display", 0, 14)); // NOI18N
        jLabel26.setText("<html>Seras redirigido a la pagina web segura <br >de mercado pago, para realizar la operacion</html>");

        panelRound8.setBackground(new java.awt.Color(170, 0, 0));
        panelRound8.setRoundBottomLeft(30);
        panelRound8.setRoundBottomRight(30);
        panelRound8.setRoundTopLeft(30);
        panelRound8.setRoundTopRight(30);

        jLabel27.setFont(new java.awt.Font("Red Hat Display", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Continuar");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel27MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound8Layout = new javax.swing.GroupLayout(panelRound8);
        panelRound8.setLayout(panelRound8Layout);
        panelRound8Layout.setHorizontalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        panelRound8Layout.setVerticalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/wallet.png"))); // NOI18N

        javax.swing.GroupLayout compDash5Layout = new javax.swing.GroupLayout(compDash5);
        compDash5.setLayout(compDash5Layout);
        compDash5Layout.setHorizontalGroup(
            compDash5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compDash5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(compDash5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(panelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        compDash5Layout.setVerticalGroup(
            compDash5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, compDash5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        compDash6.setBackground(new java.awt.Color(245, 245, 245));
        compDash6.setRoundBottomLeft(60);
        compDash6.setRoundBottomRight(60);
        compDash6.setRoundTopLeft(60);
        compDash6.setRoundTopRight(60);

        jLabel29.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel29.setText("PIN DE SEGURIDAD LOCAL");

        jLabel30.setFont(new java.awt.Font("Red Hat Display", 0, 14)); // NOI18N
        jLabel30.setText("<html>Configura el pin de seguridad local para <br >para añadir operadores y accesos</html>");

        panelRound9.setBackground(new java.awt.Color(170, 0, 0));
        panelRound9.setRoundBottomLeft(30);
        panelRound9.setRoundBottomRight(30);
        panelRound9.setRoundTopLeft(30);
        panelRound9.setRoundTopRight(30);

        jLabel31.setFont(new java.awt.Font("Red Hat Display", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Continuar");

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/tarjeta-llave.png"))); // NOI18N

        javax.swing.GroupLayout compDash6Layout = new javax.swing.GroupLayout(compDash6);
        compDash6.setLayout(compDash6Layout);
        compDash6Layout.setHorizontalGroup(
            compDash6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compDash6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(compDash6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(panelRound9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        compDash6Layout.setVerticalGroup(
            compDash6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, compDash6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        compDash7.setBackground(new java.awt.Color(245, 245, 245));
        compDash7.setRoundBottomLeft(60);
        compDash7.setRoundBottomRight(60);
        compDash7.setRoundTopLeft(60);
        compDash7.setRoundTopRight(60);

        jLabel33.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel33.setText("ESTADISTICA DE VENTAS");

        jLabel34.setFont(new java.awt.Font("Red Hat Display", 0, 14)); // NOI18N
        jLabel34.setText("<html>Visualiza los reportes y ventas<br >al dia y datos del cliente\n</html>");

        panelRound10.setBackground(new java.awt.Color(170, 0, 0));
        panelRound10.setRoundBottomLeft(30);
        panelRound10.setRoundBottomRight(30);
        panelRound10.setRoundTopLeft(30);
        panelRound10.setRoundTopRight(30);

        jLabel35.setFont(new java.awt.Font("Red Hat Display", 1, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Continuar");

        javax.swing.GroupLayout panelRound10Layout = new javax.swing.GroupLayout(panelRound10);
        panelRound10.setLayout(panelRound10Layout);
        panelRound10Layout.setHorizontalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        panelRound10Layout.setVerticalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/sale.png"))); // NOI18N

        javax.swing.GroupLayout compDash7Layout = new javax.swing.GroupLayout(compDash7);
        compDash7.setLayout(compDash7Layout);
        compDash7Layout.setHorizontalGroup(
            compDash7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compDash7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(compDash7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(panelRound10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        compDash7Layout.setVerticalGroup(
            compDash7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, compDash7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txts12.setBackground(new java.awt.Color(102, 102, 102));
        txts12.setFont(new java.awt.Font("Red Hat Display", 1, 14)); // NOI18N
        txts12.setForeground(new java.awt.Color(51, 51, 51));
        txts12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txts12.setText("Estado: Produccion");

        txts13.setBackground(new java.awt.Color(102, 102, 102));
        txts13.setFont(new java.awt.Font("Red Hat Display", 1, 14)); // NOI18N
        txts13.setForeground(new java.awt.Color(51, 51, 51));
        txts13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txts13.setText("Mercado Pago: Configurado");

        txts14.setBackground(new java.awt.Color(102, 102, 102));
        txts14.setFont(new java.awt.Font("Red Hat Display", 1, 14)); // NOI18N
        txts14.setForeground(new java.awt.Color(51, 51, 51));
        txts14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txts14.setText("Ubicacion: Belen, Cuzco, Peru");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txts12, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txts13, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txts14, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txts12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txts13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txts14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(compDash4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(compDash6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(compDash5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(compDash7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compDash5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compDash7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compDash4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compDash6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashMouseEntered
        btn.setBackground(new Color(150, 150, 150));
        btnDash.setForeground(Color.white);
        
    }//GEN-LAST:event_btnDashMouseEntered

    private void btnDashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashMouseExited
        // PREDETERMINADO -- 
        btn.setBackground(new Color(230, 230, 230));
        btnDash.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnDashMouseExited

    private void btnReporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btnReporMouseClicked

    private void btnReporMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporMouseEntered
        // Hover
        btn2.setBackground(new Color(150, 150, 150));
        btnRepor.setForeground(Color.white);
    }//GEN-LAST:event_btnReporMouseEntered

    private void btnReporMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporMouseExited
         // PREDETERMINADO -- 
        btn2.setBackground(new Color(230, 230, 230));
        btnRepor.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnReporMouseExited

    private void btnTransMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransMouseEntered
        // TODO add your handling code here:
        // Hover
        btn3.setBackground(new Color(150, 150, 150));
        btnTrans.setForeground(Color.white);
    }//GEN-LAST:event_btnTransMouseEntered

    private void btnAjustMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustMouseExited
         // PREDETERMINADO -- 
        btn4.setBackground(new Color(230, 230, 230));
        btnAjust.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnAjustMouseExited

    private void btnSoporMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSoporMouseEntered

         // Hover
        btn5.setBackground(new Color(150, 150, 150));
        btnSopor.setForeground(Color.white);
    }//GEN-LAST:event_btnSoporMouseEntered

    private void btnSoporMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSoporMouseExited
         // PREDETERMINADO -- 
        btn5.setBackground(new Color(230, 230, 230));
        btnSopor.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnSoporMouseExited

    private void btnTransMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransMouseExited
        // PREDETERMINADO -- 
        btn3.setBackground(new Color(230, 230, 230));
        btnTrans.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnTransMouseExited

    private void btnAjustMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustMouseEntered
        // Hover
        btn4.setBackground(new Color(150, 150, 150));
        btnAjust.setForeground(Color.white);
    }//GEN-LAST:event_btnAjustMouseEntered

    private void btnStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseEntered
        // TODO add your handling code here:
        btn7.setBackground(new Color(220, 0, 0));
        btnStart.setForeground(Color.white);
    }//GEN-LAST:event_btnStartMouseEntered

    private void btnStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseExited
        // TODO add your handling code here:
        btn7.setBackground(new Color(170, 0, 0));
        btnStart.setForeground(Color.white);
    }//GEN-LAST:event_btnStartMouseExited

    private void txtDispMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDispMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDispMouseClicked

    private void txtDispMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDispMousePressed
        // TODO add your handling code here:
        editDisp venClose = new editDisp();
        venClose.setVisible(true);
    }//GEN-LAST:event_txtDispMousePressed

    private void txtDispMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDispMouseEntered
        // TODO add your handling code here:
        txtDisp.setText("Editar Acceso" );
        txtDisp.setForeground(Color.gray);
        
    }//GEN-LAST:event_txtDispMouseEntered

    private void txtDispMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDispMouseExited
        // TODO add your handling code here:
        txtDisp.setText("Acceso Total" );
        txtDisp.setForeground(Color.black);
    }//GEN-LAST:event_txtDispMouseExited

    private void btnAjustMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustMousePressed
        // TODO add your handling code here:
        cerrarTodo();
        ajustes Ajustes = new ajustes();
        Ajustes.setVisible(true);
        
    }//GEN-LAST:event_btnAjustMousePressed

    private void btnStartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMousePressed
        // TODO add your handling code here:
        inicio ini = new inicio();
        ini.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnStartMousePressed

    private void jLabel27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MousePressed
             
        LoaderService loader= new LoaderService();
        loader.openLink("https://www.mercadolibre.com/jms/mpe/lgz/msl/login/H4sIAAAAAAAEAzWNwQ6DMAxD_yVnBPce9yNVVkKJ1tKqDSsT4t9JJ3G0_WyfEJLnzcovExigIwd2LDBADihLKtHyrEHMalUWeiR1BAtGEioVzNmHPM0v0lKfWjDUDuEuq11Caur9v9TjaunQ3obBNnp_mXr6NHxSsYrkaqaptTZGKg7nlNGn0aU4ZprgGpSvYqWg-4CRstN1A9UMQ8TNAAAA/user");
        
        
    }//GEN-LAST:event_jLabel27MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.interfaz.dashboard.dashboard.PanelRound bg1;
    private com.interfaz.dashboard.dashboard.PanelRound btn;
    private com.interfaz.dashboard.dashboard.PanelRound btn2;
    private com.interfaz.dashboard.dashboard.PanelRound btn3;
    private com.interfaz.dashboard.dashboard.PanelRound btn4;
    private com.interfaz.dashboard.dashboard.PanelRound btn5;
    private com.interfaz.dashboard.dashboard.PanelRound btn7;
    private javax.swing.JLabel btnAjust;
    private javax.swing.JLabel btnDash;
    private javax.swing.JLabel btnRepor;
    private javax.swing.JLabel btnSopor;
    private javax.swing.JLabel btnStart;
    private javax.swing.JLabel btnTrans;
    private com.interfaz.dashboard.dashboard.PanelRound compDash4;
    private com.interfaz.dashboard.dashboard.PanelRound compDash5;
    private com.interfaz.dashboard.dashboard.PanelRound compDash6;
    private com.interfaz.dashboard.dashboard.PanelRound compDash7;
    private com.interfaz.dashboard.dashboard.PanelRound header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.interfaz.dashboard.dashboard.PanelRound panelRound1;
    private com.interfaz.dashboard.dashboard.PanelRound panelRound10;
    private com.interfaz.dashboard.dashboard.PanelRound panelRound7;
    private com.interfaz.dashboard.dashboard.PanelRound panelRound8;
    private com.interfaz.dashboard.dashboard.PanelRound panelRound9;
    private com.interfaz.dashboard.dashboard.PanelRound showDisp;
    private javax.swing.JLabel txtDisp;
    private javax.swing.JLabel txts12;
    private javax.swing.JLabel txts13;
    private javax.swing.JLabel txts14;
    // End of variables declaration//GEN-END:variables
}
